### ISSUE TITLE
olive oil dependencies

### ISSUE THREAD

**Issue by whitead** [mfinzi/equivariant-MLP#12]
olive-oil-ml depends on pytorch, torchvision, and sklearn which makes the emlp install download about 1GB of packages even though it's a small package. Is there anyway to reduce the dependencies in olive oil, like by adding optional dependencies? Thanks!

**Comment by mfinzi** [comment]
This is a good point. We essentially only use olive-oil-ml for the experiments and datasets, so it should be possible to make it an optional dependency with some care. I will try to do that this weekend.

**Comment by mfinzi** [comment]
Hi Andrew,
I just merged this change onto master and the new v1.0.1 pypi release removes the olive-oil-ml requirement. 👍

**Comment by whitead** [comment]
Thanks for taking care of this!
